### ISSUE TITLE
Debian Linux background removal not shown in filter list, no error in log

### ISSUE THREAD

**Issue by RyanGoat** [occ-ai/obs-backgroundremoval#533] opened 2024-01-21 21:54 UTC
**Describe the bug**

Installed .deb file.  I see the plugin load in the OBS log.  But the background removal choice is not shown in the Effect Filters list.

**To Reproduce**

(Debian Linux 12, OBS Studio 29.1.2)
1. sudo dpkg -i obs-backgroundremoval-1.1.10-x86_64-linux-gnu.deb
2. sudo apt install libqt6widgets6
3. Run OBS Studio
4. Highlight Video Capture Device (V4L2)
5. Open Filters dialog
6. Open Add Filter dialog
7. Notice Background Removal choice is missing!

**Expected behavior**

Background Removal is in the list of available filters.

**Log and Crash Report**

16:37:21.399: [obs-backgroundremoval] Plugin loaded successfully (version 1.1.10)
...
16:37:21.468:   Loaded Modules:
...
16:37:21.468:     obs-backgroundremoval.so

**Desktop (please complete the following information):**

 - OS: Debian Linux 12
 - uname: Linux 6.4.0-0.deb12.2-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.4.4-3~bpo12+1 (2023-08-08) x86_64 GNU/Linux
 - Browser: n/a
 - Plugin Version: obs-backgroundremoval-1.1.10-x86_64-linux-gnu.deb
 - OBS Version: 29.1.2 (64 bit)

**Comment by agsilvio** [comment] 2024-01-22 03:02
This happens to me to on OBS version `29.0.2.1-1+b1 (64 bit)`

**Comment by umireon** [comment] 2024-01-22 09:15
@agsilvio Please post here the whole log.

**Comment by RyanGoat** [comment] 2024-01-22 12:11
Here is the full OBS log...
[2024-01-22 07-08-16.txt](https://github.com/occ-ai/obs-backgroundremoval/files/14009930/2024-01-22.07-08-16.txt)

**Comment by agsilvio** [comment] 2024-01-22 13:22
Here is my full, startup, stdout log. I could not find any other. Thank you.

[startup-stdout.log](https://github.com/occ-ai/obs-backgroundremoval/files/14010573/startup-stdout.log)

![image](https://github.com/occ-ai/obs-backgroundremoval/assets/46932979/c473df5c-2a6c-4d50-a86d-be3899af3392)

**Comment by RyanGoat** [comment] 2024-01-22 13:43
@agsilvio I think you are looking in the wrong place.  It should be under "Effects Filters".

**Comment by umireon** [comment] 2024-01-22 15:19
@agsilvio Can you open a separate issue for us to support you? Your problem is different from @RyanGoat 's one.

**Comment by umireon** [comment] 2024-01-22 15:21
@RyanGoat Can you give us some screenshots that indicate our plugin does not appear on the list?

**Comment by RyanGoat** [comment] 2024-01-22 15:29
@umireon Screenshot showing the list of available filters:
![obs bacgroundremoval filter missing](https://github.com/occ-ai/obs-backgroundremoval/assets/9138837/6b0b1160-4dc8-479a-9c12-63f3adcd4282)

**Comment by umireon** [comment] 2024-01-22 15:35
@RyanGoat We don't support Qt 5. Can you use Qt 6?

**Comment by agsilvio** [comment] 2024-01-22 17:19
> @agsilvio I think you are looking in the wrong place. It should be under "Effects Filters".

Thank you. I reached my conclusion based on this tutorial, linked on the plugin's page. Needless to say, at the time, I checked both lists of filters and it is not found. 

evidence:
![image](https://github.com/occ-ai/obs-backgroundremoval/assets/46932979/643059c4-ee2f-4f8d-8e8c-43d1dc554c4e)

**Comment by agsilvio** [comment] 2024-01-22 17:20
> @agsilvio Can you open a separate issue for us to support you? Your problem is different from @RyanGoat 's one.

Thank you but I cannot see the difference. Can you identify the difference? I am also on Debian and having the same symptoms.

**Comment by RyanGoat** [comment] 2024-01-22 17:46
> @RyanGoat We don't support Qt 5. Can you use Qt 6?

The debian stable repository package seems to be compiled against QT5.  I tried installing the latest unstable package (with OBS studio 30).  But the packaging system outsmarted me.  I'll see if I can figure out a way to get a newer build of OBS studio on my machine.

**Comment by umireon** [comment] 2024-01-23 04:41
@RyanGoat Can you install OBS and our plugin via FlatPak? FlatPak is another official distribution by OBS-Studio for other distributions than Ubuntu. (Note that Debian is not Ubuntu).

**Comment by umireon** [comment] 2024-01-23 04:43
@agsilvio Your OBS version is different from @RyanGoat 's, and this might make a huge difference. I decided to handle @agsilvio 's issue on another issue but if it reveals that the root cause was the same, we will go on the same issue.

**Comment by RyanGoat** [comment] 2024-01-23 15:38
> @RyanGoat Can you install OBS and our plugin via FlatPak? FlatPak is another official distribution by OBS-Studio for other distributions than Ubuntu. (Note that Debian is not Ubuntu).

I don't like FlatPak.  It feels like a very microsoft way to install programs.  But that is a different discussion.

I compiled obs studio 30.0.2 from source.  It is using QT 6.4.2.  Now the problem is it doesn't seem to find any plugins what so ever.  No errors in the log either.  Just no mention of any plugins at all.

**Comment by umireon** [comment] 2024-01-23 15:49
@RyanGoat, can you provide us with all the output on your terminal when you build and install OBS? Our deb package will not work with the OBS installation you compiled by yourself, and you also have to compile our plugin by yourself with proper build options.

**Comment by umireon** [comment] 2024-01-23 16:15
#537 will close this issue.

**Closed** 2024-01-23 18:37 UTC
Labels: bug

**Comment by thedeveloperdavid** [comment] 2024-04-21 02:43
.deb release is not for debian users, only ubuntu. The package don't respect the official stable debian dependencies and is useless on debian.

flatpak is not a system solution, is a container solution and don't respect the path's and plugins of inner system.

Bottom line: only ubuntu is supported.

**Comment by umireon** [comment] 2024-04-21 09:30
@thedeveloperdavid I don't think the OBS project supports Debian officially so that you have to build our plugin by youself and this restriction is intended.
