### ISSUE TITLE
Version 1.1.13 doesn't work

### ISSUE THREAD

**Issue by smnbgn** [occ-ai/obs-backgroundremoval#570] opened 2024-03-29 21:16 UTC
Version 1.1.13 doesn't work on my computer, but 1.1.12 does.

The processor is AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx.

**Comment by umireon** [comment] 2024-03-30 01:01
Please post there the OBS log and the screenshot.

**Comment by smnbgn** [comment] 2024-03-30 06:32
Here is the log. Nothing happens in OBS, it just doesn't remove the background.
[backgroundremoveal_obs.txt](https://github.com/occ-ai/obs-backgroundremoval/files/14810882/backgroundremoveal_obs.txt)

**Comment by umireon** [comment] 2024-03-30 08:20
OK. Then can we close this issue?

**Comment by smnbgn** [comment] 2024-03-30 08:27
I don't think so. The setting GPU - DirectML works under version 1.1.12.

**Comment by umireon** [comment] 2024-03-30 08:28
You are on Windows?

**Comment by smnbgn** [comment] 2024-03-30 08:32
Windows 10, yes.

**Comment by umireon** [comment] 2024-03-30 08:39
How do you install our plugin?

**Comment by smnbgn** [comment] 2024-03-30 09:11
https://github.com/occ-ai/obs-backgroundremoval/releases/download/1.1.13/obs-backgroundremoval-1.1.13-windows-x64-Installer.exe

**Comment by umireon** [comment] 2024-03-30 09:42
Unfortunately, we don't have any Windows 10 machine. Can you investigate the root cause of this error and cotribute back to our repository?

Maybe related to https://github.com/microsoft/onnxruntime/issues/19405

I think this might be an upstream issue.

**Comment by umireon** [comment] 2024-03-30 09:44
The version of ONNX Runtime have been upgraded from 1.16.3 to 1.17.1 at obs-backgroundremoval 1.1.13.

**Comment by KenCarter01** [comment] 2024-04-06 13:27
Same issue for me.

**Comment by umireon** [comment] 2024-04-06 15:40
@royshil Can we close this issue as lack of information?

**Comment by umireon** [comment] 2024-04-06 15:41
We need another person who can provide the detail of this bug.

**Comment by smnbgn** [comment] 2024-04-06 15:47
> Unfortunately, we don't have any Windows 10 machine. Could you please investigate the root cause of this error and contribute back to our repository?

I can't even build the plugin on Windows because of outdated sources in the scripts.

**Comment by umireon** [comment] 2024-04-06 15:53
Closing this issue as this got a catch-all issue

**Closed by umireon** 2024-04-06 15:53 UTC
Labels: bug, question

**Comment by umireon** [comment] 2024-04-06 15:57
I believe our code can be built without problems on Windows and it should be a problem specific to your enivironment.
